services:
  sd-webui:
    image: andrespt/sd-webui:0.3
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "7860"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../models:/content/stable-diffusion-webui/models
      - ../outputs:/content/stable-diffusion-webui/outputs
      - home:/root
    command: python3 launch.py --listen
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


volumes:
  home: